services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=spring_app_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql:Z

volumes:
  pg_data: